version: "3.8"
services:
  db:
    image: open-room-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "*sametSis1!"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    image: open-room-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/api
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: "*sametSis1!"
volumes:
  db-data:
