FROM postgres:16-alpine

# Set environment variables for the database (adjust as needed)
ENV POSTGRES_DB=api
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=*sametSis1!

# Copy the initialization script
COPY init.sql /docker-entrypoint-initdb.d/
